create database Avtaar;
use Avtaar;

create table user(uid int NOT NULL auto_increment,username varchar(100) NOT NULL,gender ENUM('MALE','FEMALE'),email varchar(100) NOT NULL UNIQUE,primary key(uid));
insert into user(uid,username,gender,email)values(1,'Sayali Selukar','Female','sselukar@gmail.com');
insert into user(uid,username,gender,email)values(2,'Rohan Selukar','Male','rohans@gmail.com');
insert into user(uid,username,gender,email)values(3,'Jerusha Gaikwad','Female','jerry@gmail.com');
insert into user(uid,username,gender,email)values(4,'Athira Sasidharan','Female','sathira@gmail.com');
insert into user(uid,username,gender,email)values(5,'Dhanashree Gandas','Female','dhanashreeg@gmail.com');
insert into user(uid,username,gender,email)values(6,'Jayateerth Kakhandki','Male','jayk@gmail.com');
insert into user(uid,username,gender,email)values(7,'Nachiket Suryavanshi','Male','nachikets@gmail.com');
insert into user(uid,username,gender,email)values(8,'Vidya Londhe','Female','vlondhe@gmail.com');
insert into user(uid,username,gender,email)values(9,'Amruta Misal','Female','amumisal@gmail.com');
insert into user(uid,username,gender,email)values(10,'Aishwarya Kate','Female','aishkate@gmail.com');
insert into user(uid,username,gender,email)values(11,'Anish Dubey','Male','anishdubey@gmail.com');
insert into user(uid,username,gender,email)values(12,'Prathmesh Yadav','Male','pyadav@gmail.com');
insert into user(uid,username,gender,email)values(13,'Mayuri Magar','Female','mmagar@gmail.com');
insert into user(uid,username,gender,email)values(14,'Varad Selukar','Male','varad777@gmail.com');
insert into user(uid,username,gender,email)values(15,'Rutik Revankar','Male','rutik04@gmail.com');
select * from  user;